linters:
  enable-all: true
  disable:
  - exhaustivestruct
  - forbidigo
  - gochecknoglobals
  - ireturn
  - nlreturn
  - testpackage
  - varnamelen

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - funlen
    - interfacer
    - maligned
    - nilnil
    - noctx
    - scopelint
